name: restaurant-catalog

volumes:
  postgres_data:

services:
  db:
    image: postgres:15-alpine
    env_file: ../../src/backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../../src/backend  # Контекст сборки — это директория с исходным кодом
      dockerfile: ../../devops/docker/Dockerfile
    env_file: ../../src/backend/.env
    volumes:
      - ../../src/backend:/app  # Монтируем только директорию backend
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy